# Site settings
author: Matthew
title: Oh, Technology
header-img: img/home-bg.png
email: matthew.lewandowski@wework.com
copyright_name: Matthew
description: > # this means to ignore newlines until "baseurl:"
  Sometimes to go forward, you have to go backward
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  LithiumSquid

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
